package fr.tunaki.stackoverflow.burnaki.entity;
// Generated 15 ao�t 2016 00:59:03 by Hibernate Tools 4.3.4.Final

import java.io.Serializable;
import java.time.Instant;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;

/**
 * BurninationQuestionHistory generated by hbm2java
 */
@Entity
@Table(name = "burnination_question_history")
public class BurninationQuestionHistory implements Serializable {

	private static final long serialVersionUID = -1978028433062733596L;
	
	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "eventDate", column = @Column(name = "event_date", nullable = false, length = 19))
	})
	private BurninationQuestionHistoryId id;
	
	@MapsId("burninationQuestionId")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "burnination_id", referencedColumnName = "burnination_id", nullable = false),
		@JoinColumn(name = "question_id", referencedColumnName = "question_id", nullable = false)
	})
	private BurninationQuestion burninationQuestion;
	
	@Column(name = "event_type", nullable = false, length = 45)
	private String eventType;
	
	public BurninationQuestionHistory() { }

	public BurninationQuestionHistory(BurninationQuestion burninationQuestion, String eventType, Instant eventDate) {
		id = new BurninationQuestionHistoryId();
		id.setBurninationQuestionId(burninationQuestion.getId());
		id.setEventDate(eventDate);
		this.eventType = eventType;
	}

	public BurninationQuestionHistoryId getId() {
		return id;
	}

	public BurninationQuestion getBurninationQuestion() {
		return burninationQuestion;
	}

	public void setBurninationQuestion(BurninationQuestion burninationQuestion) {
		this.burninationQuestion = burninationQuestion;
	}
	
	public String getEventType() {
		return eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

}
